language: python
# Which versions of Python to test
python:
  - "2.7"
# Have the virtualenv use system-wide site packages
virtualenv:
    system_site_packages: true
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git python-dev sqlite3
  - sudo pip install --upgrade numpy matplotlib scipy scikit-image
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - git checkout 2.4.13.2
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make -j4 install
  - cd ../..
# Install PlantCV
install:
  - python setup.py install
# command to run tests
script: py.test -v tests/tests.py
# Which branches to run build tests on
branches:
  only:
    - dev
