language: python
# Which versions of Python to test
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git libopencv-dev python-opencv python-numpy python-matplotlib sqlite3
  - python -c 'import sys;print(sys.path)'
# Install PlantCV
install:
  - sudo python setup.py install
# command to run tests
script: python tests/tests.py
# Which branches to run build tests on
branches:
  only:
    - feature-setuptools
