site_name: PlantCV
site_url: http://plantcv.readthedocs.io/
site_description: Plant phenotyping using computer vision
site_author: PlantCV Development Team
repo_url: https://github.com/danforthcenter/plantcv

pages:
- Home: index.md
- Documentation:
  - Installation: installation.md
  - Tutorials:
    - 'VIS pipeline': vis_tutorial.md
  - Library:
    - 'Analyze color': analyze_color.md
    - 'Analyze shape': analyze_shape.md
    - 'Apply mask': apply_mask.md
    - 'Binary threshold': binary_threshold.md
    - 'Boundary line tool': analyze_bound.md
    - 'Erosion': erode.md
    - 'Fill objects': fill.md
    - 'Find objects': find_objects.md
    - 'Image add': image_add.md
    - 'Image subtract': image_subtract.md
    - 'Median blur': median_blur.md
    - 'Print image': print_image.md
    - 'Read image': read_image.md
    - 'RGB to HSV': rgb2hsv.md
    - 'RGB to LAB': rgb2lab.md

markdown_extensions:
  - toc:
      permalink: True
