site_name: PlantCV
site_url: http://plantcv.readthedocs.io/
site_description: Plant phenotyping using computer vision
site_author: PlantCV Development Team
repo_url: https://github.com/danforthcenter/plantcv
copyright: Copyright 2016, Donald Danforth Plant Science Center

pages:
- Home: index.md
- Documentation:
  - Installation: installation.md
  - 'Using Jupyter Notebooks': jupyter.md
  - 'Adding/editing Documentation': documentation.md
  - Tutorials:
    - 'VIS pipeline': vis_tutorial.md
    - 'NIR pipeline': nir_tutorial.md
    - 'PSII pipeline': psII_tutorial.md
    - 'VIS/NIR dual pipeline': vis_nir_tutorial.md
    - 'Pipeline parallelization': pipeline_parallel.md
  - Library:
    - 'Adaptive Threshold': adaptive_threshold.md
    - 'Analyze color': analyze_color.md
    - 'Analyze NIR': analyze_NIR_intensity.md
    - 'Analyze PSII': fluor_fvfm.md
    - 'Analyze shape': analyze_shape.md
    - 'Apply mask': apply_mask.md
    - 'Binary threshold': binary_threshold.md
    - 'Boundary line tool': analyze_bound.md
    - 'Crop and Position Mask': crop_position_mask.md
    - 'Dilation': dilate.md
    - 'Erosion': erode.md
    - 'Fill objects': fill.md
    - 'Find objects': find_objects.md
    - 'Flip image': flip.md
    - 'Gaussian Blur': gaussian_blur.md
    - 'Get NIR images': get_nir.md
    - 'Erosion': erode.md
    - 'Fill objects': fill.md
    - 'Find objects': find_objects.md
    - 'Histogram normalization': HistEqualization.md
    - 'Image add': image_add.md
    - 'Image subtract': image_subtract.md
    - 'Invert': invert.md
    - 'Laplace filter': laplace_filter.md
    - 'Logical operations-And': logical_and.md
    - 'Logical operations-Or': logical_or.md
    - 'Median blur': median_blur.md
    - 'Object composition': object_composition.md
    - 'Otsu Auto Threshold': otsu_threshold.md
    - 'Plot histogram': plot_hist.md
    - 'Print image': print_image.md
    - 'Read image': read_image.md
    - 'Rectangle mask': rectangle_mask.md
    - 'Region of interest-Define': define_roi.md
    - 'Region of interest-Objects': roi_objects.md
    - 'Resize': resize.md
    - 'RGB to HSV': rgb2hsv.md
    - 'RGB to LAB': rgb2lab.md
    - 'Rotate Image': rotate.md
    - 'Shift Image': shift.md
    - 'Sobel filter': sobel_filter.md
    - 'White balance': white_balance.md

markdown_extensions:
  - toc:
      permalink: True
