# run: conda env create --file environment27.yml
name: test-environment
dependencies:
  - python=2.7
  - matplotlib>=1.5
  - numpy>=1.11
  - pandas
  - python-dateutil
  - scipy
  - scikit-image
  - pytest
  - plotnine
  - coveralls
  - nb_conda
  - pip:
    - opencv-python
channels:
  - conda-forge
