project_url: http://plantcv.danforthcenter.org/
doc_url: http://plantcv.readthedocs.io/
repo_url: https://github.com/danforthcenter/plantcv

pages:
- Home: index.md
- Documentation:
	- Installation: installation.md
    - Library:
        - Convert RGB to Gray:
            - RGB to HSV: rgb2hsv.md